### ISSUE TITLE
Url variable

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-role-perfsonar-maddash#1]
Hello!
```
# defaults file for perfsonar-maddash
# perfsonar_maddash_remotes:
#   - state: [ present | absent ]
#   - url: url
perfsonar_maddash_remotes: []
```
Is `url `variable of url of where mesh.json is published(json file similar https://github.com/perfsonar/ansible-role-perfsonar-psconfig-publisher/blob/master/files/skeleton.json)?

**Comment by epcjr** [comment]
Yes, that is correct.  Someone could modify skeleton.json to include real
configuration information, publish it at a URL, and use that URL as an
entry in the perfsonar_maddash_remotes list.

Thanks,

-Ed
